name: Build and Release

on: push
  # push:
  #   branches: [ "main", "master" ]

jobs:
  call_check_version:
    uses: ./.github/workflows/check_version.yml

  build_and_release:
    runs-on: windows-latest
    needs: call_check_version
    if: always() && (needs.call_check_version.result == 'success')

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
          5.0.x
          7.0.x

    - name: Restore dependencies
      run: dotnet restore

    ## Might as well build and test since we're here
    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    ## This lets us build the electron app
    - name: Install ElectronNET.CLI
      run: dotnet tool install ElectronNET.CLI -g

    - name: Build Release Artifact
      shell: bash
      run: |
        cd GUI && electronize build /target win
