name: Build and Release

on: push
  # push:
  #   branches: [ "main", "master" ]

jobs:
  call_check_version:
    uses: ./.github/workflows/check_version.yml

  build_and_test:
    runs-on: windows-latest
    needs: call_check_version
    if: always() && (needs.call_check_version.result == 'success')

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
          5.0.x
          7.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

  ## Will be set up for releasing soon -- still testing right now
